<a href="https://colab.research.google.com/github/LambdaTheda/DS-Unit-2-Linear-Models/blob/master/8pm_S_Mar_7_build_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# read in dataset 1: pokemon Go character sightings

import pandas as pd

df = pd.read_csv('300k.csv')
pd.set_option("display.max_rows", 91835)
#pd.set_option("display.max_columns", 300)
df

In [0]:
df.shape

(203081, 208)

In [0]:
df.head()

   pokemonId   latitude   longitude  ... cooc_150 cooc_151  class
0         16  20.525745  -97.460829  ...    False    False   16.0
1        133  20.523695  -97.461167  ...    False    False  133.0
2         16  38.903590  -77.199780  ...    False    False   16.0
3         13  47.665903 -122.312561  ...    False    False   13.0
4        133  47.666454 -122.311628  ...    False    False  133.0

[5 rows x 208 columns]

In [0]:
# read in dataset 2: encoded names and corresponding id#s
df_Names = pd.read_csv('pokemonNumbers.csv', header= None)
pd.set_option("display.max_rows", 91835)
df_Names

In [0]:
df_Names.head()

   0           1
0  1   Bulbasaur
1  2     Ivysaur
2  3    Venusaur
3  4  Charmander
4  5  Charmeleon

In [0]:
df_Names.shape

In [0]:
#EXPLORATORY DATA ANALYSIS/DATA WRANGLING

# change df_Names column names
df_Names.columns=['pokeID_num_From_df_Names', 'pokemonName']
df_Names

In [0]:
# check df_Names column datatypes
print(df_Names.dtypes)

pokeID_num_From_df_Names     int64
pokemonName                 object
dtype: object

In [0]:
# join df and df_Names using .concat for union of dfs - WORKS but GET NaNs
'''
df3 =  pd.concat([df_Names, df], axis=1, sort=False)
pd.set_option("display.max_rows", 91835)
df3
'''

'\ndf3 =  pd.concat([df_Names, df], axis=1, sort=False)\npd.set_option("display.max_rows", 91835)\ndf3\n'

In [0]:
# merge df and df_Names using -NOT WORK
# df_Names.merge(df, left_on='pokemonName', right_on='pokemonId')

In [0]:
# MATCH or REPLACE pokemonId with pokemonName

# 1. convert df_Names into a dictionary

In [0]:
# check Nulls- returns 0 for all columns
df.isnull().sum()

pokemonId                 0
latitude                  0
longitude                 0
appearedLocalTime         0
_id                       0
cellId_90m                0
cellId_180m               0
cellId_370m               0
cellId_730m               0
cellId_1460m              0
cellId_2920m              0
cellId_5850m              0
appearedTimeOfDay         0
appearedHour              0
appearedMinute            0
appearedDayOfWeek         0
appearedDay               0
appearedMonth             0
appearedYear              0
terrainType               0
closeToWater              0
city                      0
continent                 0
weather                   0
temperature               0
windSpeed                 0
windBearing               0
pressure                  0
weatherIcon               0
sunriseMinutesMidnight    0
sunriseHour               0
sunriseMinute             0
sunriseMinutesSince       0
sunsetMinutesMidnight     0
sunsetHour                0
sunsetMinute              0
sunsetMinutesBefore       0
population_density        0
urban                     0
suburban                  0
midurban                  0
rural                     0
gymDistanceKm             0
gymIn100m                 0
gymIn250m                 0
gymIn500m                 1
gymIn1000m                1
gymIn2500m                1
gymIn5000m                1
pokestopDistanceKm        1
pokestopIn100m            1
pokestopIn250m            1
pokestopIn500m            1
pokestopIn1000m           1
pokestopIn2500m           1
pokestopIn5000m           1
cooc_1                    1
cooc_2                    1
cooc_3                    1
cooc_4                    1
cooc_5                    1
cooc_6                    1
cooc_7                    1
cooc_8                    1
cooc_9                    1
cooc_10                   1
cooc_11                   1
cooc_12                   1
cooc_13                   1
cooc_14                   1
cooc_15                   1
cooc_16                   1
cooc_17                   1
cooc_18                   1
cooc_19                   1
cooc_20                   1
cooc_21                   1
cooc_22                   1
cooc_23                   1
cooc_24                   1
cooc_25                   1
cooc_26                   1
cooc_27                   1
cooc_28                   1
cooc_29                   1
cooc_30                   1
cooc_31                   1
cooc_32                   1
cooc_33                   1
cooc_34                   1
cooc_35                   1
cooc_36                   1
cooc_37                   1
cooc_38                   1
cooc_39                   1
cooc_40                   1
cooc_41                   1
cooc_42                   1
cooc_43                   1
cooc_44                   1
cooc_45                   1
cooc_46                   1
cooc_47                   1
cooc_48                   1
cooc_49                   1
cooc_50                   1
cooc_51                   1
cooc_52                   1
cooc_53                   1
cooc_54                   1
cooc_55                   1
cooc_56                   1
cooc_57                   1
cooc_58                   1
cooc_59                   1
cooc_60                   1
cooc_61                   1
cooc_62                   1
cooc_63                   1
cooc_64                   1
cooc_65                   1
cooc_66                   1
cooc_67                   1
cooc_68                   1
cooc_69                   1
cooc_70                   1
cooc_71                   1
cooc_72                   1
cooc_73                   1
cooc_74                   1
cooc_75                   1
cooc_76                   1
cooc_77                   1
cooc_78                   1
cooc_79                   1
cooc_80                   1
cooc_81                   1
cooc_82                   1
cooc_83                   1
cooc_84                   1
cooc_85                   1
cooc_86                   1
cooc_87                   1
cooc_88                   1
cooc_89                   1
cooc_90                   1
cooc_91                   1
cooc_92                   1
cooc_93                   1
cooc_94                   1
cooc_95                   1
cooc_96                   1
cooc_97                   1
cooc_98                   1
cooc_99                   1
cooc_100                  1
cooc_101                  1
cooc_102                  1
cooc_103                  1
cooc_104                  1
cooc_105                  1
cooc_106                  1
cooc_107                  1
cooc_108                  1
cooc_109                  1
cooc_110                  1
cooc_111                  1
cooc_112                  1
cooc_113                  1
cooc_114                  1
cooc_115                  1
cooc_116                  1
cooc_117                  1
cooc_118                  1
cooc_119                  1
cooc_120                  1
cooc_121                  1
cooc_122                  1
cooc_123                  1
cooc_124                  1
cooc_125                  1
cooc_126                  1
cooc_127                  1
cooc_128                  1
cooc_129                  1
cooc_130                  1
cooc_131                  1
cooc_132                  1
cooc_133                  1
cooc_134                  1
cooc_135                  1
cooc_136                  1
cooc_137                  1
cooc_138                  1
cooc_139                  1
cooc_140                  1
cooc_141                  1
cooc_142                  1
cooc_143                  1
cooc_144                  1
cooc_145                  1
cooc_146                  1
cooc_147                  1
cooc_148                  1
cooc_149                  1
cooc_150                  1
cooc_151                  1
class                     1
dtype: int64

In [0]:

#drop df cols with nulls
#df.dropna() - not work right
df.dropna(axis='columns') # also not work right
df

        pokemonId   latitude   longitude  ... cooc_150 cooc_151  class
0              16  20.525745  -97.460829  ...    False    False   16.0
1             133  20.523695  -97.461167  ...    False    False  133.0
2              16  38.903590  -77.199780  ...    False    False   16.0
3              13  47.665903 -122.312561  ...    False    False   13.0
4             133  47.666454 -122.311628  ...    False    False  133.0
...           ...        ...         ...  ...      ...      ...    ...
183789         23  18.156010  -67.141550  ...    False    False   23.0
183790         41  48.742799    2.405089  ...    False    False   41.0
183791        102  37.547138  -77.449356  ...    False    False  102.0
183792         13  38.558872  -92.197425  ...    False    False   13.0
183793        111  40.045760 -105.252897  ...      NaN      NaN    NaN

[183794 rows x 208 columns]

In [0]:
df.isnull().sum()

pokemonId                 0
latitude                  0
longitude                 0
appearedLocalTime         0
_id                       0
cellId_90m                0
cellId_180m               0
cellId_370m               0
cellId_730m               0
cellId_1460m              0
cellId_2920m              0
cellId_5850m              0
appearedTimeOfDay         0
appearedHour              0
appearedMinute            0
appearedDayOfWeek         0
appearedDay               0
appearedMonth             0
appearedYear              0
terrainType               0
closeToWater              0
city                      0
continent                 0
weather                   0
temperature               0
windSpeed                 0
windBearing               0
pressure                  0
weatherIcon               0
sunriseMinutesMidnight    0
sunriseHour               0
sunriseMinute             0
sunriseMinutesSince       0
sunsetMinutesMidnight     0
sunsetHour                0
sunsetMinute              0
sunsetMinutesBefore       0
population_density        0
urban                     0
suburban                  0
midurban                  0
rural                     0
gymDistanceKm             0
gymIn100m                 0
gymIn250m                 0
gymIn500m                 1
gymIn1000m                1
gymIn2500m                1
gymIn5000m                1
pokestopDistanceKm        1
pokestopIn100m            1
pokestopIn250m            1
pokestopIn500m            1
pokestopIn1000m           1
pokestopIn2500m           1
pokestopIn5000m           1
cooc_1                    1
cooc_2                    1
cooc_3                    1
cooc_4                    1
cooc_5                    1
cooc_6                    1
cooc_7                    1
cooc_8                    1
cooc_9                    1
cooc_10                   1
cooc_11                   1
cooc_12                   1
cooc_13                   1
cooc_14                   1
cooc_15                   1
cooc_16                   1
cooc_17                   1
cooc_18                   1
cooc_19                   1
cooc_20                   1
cooc_21                   1
cooc_22                   1
cooc_23                   1
cooc_24                   1
cooc_25                   1
cooc_26                   1
cooc_27                   1
cooc_28                   1
cooc_29                   1
cooc_30                   1
cooc_31                   1
cooc_32                   1
cooc_33                   1
cooc_34                   1
cooc_35                   1
cooc_36                   1
cooc_37                   1
cooc_38                   1
cooc_39                   1
cooc_40                   1
cooc_41                   1
cooc_42                   1
cooc_43                   1
cooc_44                   1
cooc_45                   1
cooc_46                   1
cooc_47                   1
cooc_48                   1
cooc_49                   1
cooc_50                   1
cooc_51                   1
cooc_52                   1
cooc_53                   1
cooc_54                   1
cooc_55                   1
cooc_56                   1
cooc_57                   1
cooc_58                   1
cooc_59                   1
cooc_60                   1
cooc_61                   1
cooc_62                   1
cooc_63                   1
cooc_64                   1
cooc_65                   1
cooc_66                   1
cooc_67                   1
cooc_68                   1
cooc_69                   1
cooc_70                   1
cooc_71                   1
cooc_72                   1
cooc_73                   1
cooc_74                   1
cooc_75                   1
cooc_76                   1
cooc_77                   1
cooc_78                   1
cooc_79                   1
cooc_80                   1
cooc_81                   1
cooc_82                   1
cooc_83                   1
cooc_84                   1
cooc_85                   1
cooc_86                   1
cooc_87                   1
cooc_88                   1
cooc_89                   1
cooc_90                   1
cooc_91                   1
cooc_92                   1
cooc_93                   1
cooc_94                   1
cooc_95                   1
cooc_96                   1
cooc_97                   1
cooc_98                   1
cooc_99                   1
cooc_100                  1
cooc_101                  1
cooc_102                  1
cooc_103                  1
cooc_104                  1
cooc_105                  1
cooc_106                  1
cooc_107                  1
cooc_108                  1
cooc_109                  1
cooc_110                  1
cooc_111                  1
cooc_112                  1
cooc_113                  1
cooc_114                  1
cooc_115                  1
cooc_116                  1
cooc_117                  1
cooc_118                  1
cooc_119                  1
cooc_120                  1
cooc_121                  1
cooc_122                  1
cooc_123                  1
cooc_124                  1
cooc_125                  1
cooc_126                  1
cooc_127                  1
cooc_128                  1
cooc_129                  1
cooc_130                  1
cooc_131                  1
cooc_132                  1
cooc_133                  1
cooc_134                  1
cooc_135                  1
cooc_136                  1
cooc_137                  1
cooc_138                  1
cooc_139                  1
cooc_140                  1
cooc_141                  1
cooc_142                  1
cooc_143                  1
cooc_144                  1
cooc_145                  1
cooc_146                  1
cooc_147                  1
cooc_148                  1
cooc_149                  1
cooc_150                  1
cooc_151                  1
class                     1
dtype: int64

In [0]:
df.columns.to_list()

['pokemonId',
 'latitude',
 'longitude',
 'appearedLocalTime',
 '_id',
 'cellId_90m',
 'cellId_180m',
 'cellId_370m',
 'cellId_730m',
 'cellId_1460m',
 'cellId_2920m',
 'cellId_5850m',
 'appearedTimeOfDay',
 'appearedHour',
 'appearedMinute',
 'appearedDayOfWeek',
 'appearedDay',
 'appearedMonth',
 'appearedYear',
 'terrainType',
 'closeToWater',
 'city',
 'continent',
 'weather',
 'temperature',
 'windSpeed',
 'windBearing',
 'pressure',
 'weatherIcon',
 'sunriseMinutesMidnight',
 'sunriseHour',
 'sunriseMinute',
 'sunriseMinutesSince',
 'sunsetMinutesMidnight',
 'sunsetHour',
 'sunsetMinute',
 'sunsetMinutesBefore',
 'population_density',
 'urban',
 'suburban',
 'midurban',
 'rural',
 'gymDistanceKm',
 'gymIn100m',
 'gymIn250m',
 'gymIn500m',
 'gymIn1000m',
 'gymIn2500m',
 'gymIn5000m',
 'pokestopDistanceKm',
 'pokestopIn100m',
 'pokestopIn250m',
 'pokestopIn500m',
 'pokestopIn1000m',
 'pokestopIn2500m',
 'pokestopIn5000m',
 'cooc_1',
 'cooc_2',
 'cooc_3',
 'cooc_4',
 'cooc_5',
 'cooc_6',
 'cooc_7',
 'cooc_8',
 'cooc_9',
 'cooc_10',
 'cooc_11',
 'cooc_12',
 'cooc_13',
 'cooc_14',
 'cooc_15',
 'cooc_16',
 'cooc_17',
 'cooc_18',
 'cooc_19',
 'cooc_20',
 'cooc_21',
 'cooc_22',
 'cooc_23',
 'cooc_24',
 'cooc_25',
 'cooc_26',
 'cooc_27',
 'cooc_28',
 'cooc_29',
 'cooc_30',
 'cooc_31',
 'cooc_32',
 'cooc_33',
 'cooc_34',
 'cooc_35',
 'cooc_36',
 'cooc_37',
 'cooc_38',
 'cooc_39',
 'cooc_40',
 'cooc_41',
 'cooc_42',
 'cooc_43',
 'cooc_44',
 'cooc_45',
 'cooc_46',
 'cooc_47',
 'cooc_48',
 'cooc_49',
 'cooc_50',
 'cooc_51',
 'cooc_52',
 'cooc_53',
 'cooc_54',
 'cooc_55',
 'cooc_56',
 'cooc_57',
 'cooc_58',
 'cooc_59',
 'cooc_60',
 'cooc_61',
 'cooc_62',
 'cooc_63',
 'cooc_64',
 'cooc_65',
 'cooc_66',
 'cooc_67',
 'cooc_68',
 'cooc_69',
 'cooc_70',
 'cooc_71',
 'cooc_72',
 'cooc_73',
 'cooc_74',
 'cooc_75',
 'cooc_76',
 'cooc_77',
 'cooc_78',
 'cooc_79',
 'cooc_80',
 'cooc_81',
 'cooc_82',
 'cooc_83',
 'cooc_84',
 'cooc_85',
 'cooc_86',
 'cooc_87',
 'cooc_88',
 'cooc_89',
 'cooc_90',
 'cooc_91',
 'cooc_92',
 'cooc_93',
 'cooc_94',
 'cooc_95',
 'cooc_96',
 'cooc_97',
 'cooc_98',
 'cooc_99',
 'cooc_100',
 'cooc_101',
 'cooc_102',
 'cooc_103',
 'cooc_104',
 'cooc_105',
 'cooc_106',
 'cooc_107',
 'cooc_108',
 'cooc_109',
 'cooc_110',
 'cooc_111',
 'cooc_112',
 'cooc_113',
 'cooc_114',
 'cooc_115',
 'cooc_116',
 'cooc_117',
 'cooc_118',
 'cooc_119',
 'cooc_120',
 'cooc_121',
 'cooc_122',
 'cooc_123',
 'cooc_124',
 'cooc_125',
 'cooc_126',
 'cooc_127',
 'cooc_128',
 'cooc_129',
 'cooc_130',
 'cooc_131',
 'cooc_132',
 'cooc_133',
 'cooc_134',
 'cooc_135',
 'cooc_136',
 'cooc_137',
 'cooc_138',
 'cooc_139',
 'cooc_140',
 'cooc_141',
 'cooc_142',
 'cooc_143',
 'cooc_144',
 'cooc_145',
 'cooc_146',
 'cooc_147',
 'cooc_148',
 'cooc_149',
 'cooc_150',
 'cooc_151',
 'class']

In [0]:
#trim df to reduce noise including nulls
df_trimmed = df.drop(columns=['gymIn100m',
 'gymIn250m',
 'gymIn500m',
 'gymIn1000m',
 'gymIn2500m',
 'gymIn5000m',
 'cooc_114',
 'cooc_115',
 'cooc_116',
 'cooc_117',
 'cooc_118',
 'cooc_119',
 'cooc_120',
 'cooc_121',
 'cooc_122',
 'cooc_123',
 'cooc_124',
 'cooc_125',
 'cooc_126',
 'cooc_127',
 'cooc_128',
 'cooc_129',
 'cooc_130',
 'cooc_131',
 'cooc_132',
 'cooc_133',
 'cooc_134',
 'cooc_135',
 'cooc_136',
 'cooc_137',
 'cooc_138',
 'cooc_139',
 'cooc_140',
 'cooc_141',
 'cooc_142',
 'cooc_143',
 'cooc_144',
 'cooc_145',
 'cooc_146',
 'cooc_147',
 'cooc_148',
 'cooc_149',
 'cooc_150',
 'cooc_151',
 ])

In [0]:
df_trimmed

        pokemonId   latitude   longitude  ... cooc_112 cooc_113  class
0              16  20.525745  -97.460829  ...    False    False   16.0
1             133  20.523695  -97.461167  ...    False    False  133.0
2              16  38.903590  -77.199780  ...    False    False   16.0
3              13  47.665903 -122.312561  ...    False    False   13.0
4             133  47.666454 -122.311628  ...    False    False  133.0
...           ...        ...         ...  ...      ...      ...    ...
183789         23  18.156010  -67.141550  ...    False    False   23.0
183790         41  48.742799    2.405089  ...    False    False   41.0
183791        102  37.547138  -77.449356  ...    False    False  102.0
183792         13  38.558872  -92.197425  ...    False    False   13.0
183793        111  40.045760 -105.252897  ...      NaN      NaN    NaN

[183794 rows x 164 columns]

In [0]:
#df_trimmed.sort_by('pokemonId', ascending = True)

In [0]:
#check data distribution to see if linear model is appropriate- IT IS NOT; THIS IS MULTI-CLASS CLASSIFICATiON PROBLEM
df_trimmed.plot.hist()

In [0]:
df_trimmed.isnull().sum()

In [0]:
#Get BASELINE- the first way to get the highest accuracy by assuming majority, [by] assum[ing] majority:

pd.set_option('display.max_columns', 500)
pd.set_option('display.max_row', 300000)
'''
average for regression should be the majority value in a sense; 
classification is assuming all values are the highest majority value- BASELINE IS PREDICTING MODE CLASS (largest # of observations
'''

df['appearedDayOfWeek'].value_counts()
# our BASELINE IS SATURDAY, WITH 72201 appearances on that day

Saturday     72201
Friday       68037
Sunday       32056
dummy_day     9001
Thursday      2499
Name: appearedDayOfWeek, dtype: int64

In [0]:
df['appearedDayOfWeek'].nunique()

5

In [0]:
# Fit a Classification model
# Try a shallow decision tree as a fast, first model

#pip install --upgrade category_encoders
# from sklearn.preprocessing import CategoricalEncoder
#pip install category_encoders

!pip install category_encoders==2.* 

import numpy as np
import category_encoders as ce
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split

#encoder = ce.OrdinalEncoder(cols=[...])

target = 'appearedDayOfWeek'
features = ['appearedMonth', 'appearedYear', 'appearedDay', 'pokestopDistanceKm', 'weather', 'latitude', 'longitude']

#train = df 

X_train, X_test, y_train, y_test = train_test_split(df[features], df[target])
train, test = train_test_split(df)

pipeline = make_pipeline(
    ce.OrdinalEncoder(),
    SimpleImputer(strategy='most_frequent'),
    RandomForestClassifier()
)

In [0]:
# function to Convert 'appearedDayOfWeek' string values into floats

'''
def convertDayToFloat():

    week = list(df['appearedDayOfWeek'].replace('1.0', '2.0', '3.0','4.0','5.0','6.0','7.0'))

    print(week)

convertDayToFloat
'''

"\ndef convertDayToFloat():\n\n    week = list(df['appearedDayOfWeek'].replace('1.0', '2.0', '3.0','4.0','5.0','6.0','7.0'))\n\n    print(week)\n\nconvertDayToFloat\n"

In [0]:
#dictionary to Convert 'appearedDayOfWeek' string values into floats

dict = {'Sunday':'1.0', 'dummy_day':'2.0', 'Tuesday':'3.0','Wednesday':'4.0','Thursday':'5.0', 'Friday':'6.0', 'Saturday':'7.0' }

In [0]:
#fit model 1: Random Forest Classifier and score accuracy

In [0]:

pipeline.fit(X_train, y_train)
acc_score = pipeline.score(test[features], test[target])
#ra_score = roc_auc_score(test[target], pipeline.predict(test[features]))

print(f'Test Accuracy: {pipeline.score(X_test, y_test)}')
print(f'Test ROC AUC: {roc_auc_score(y_test, pipeline.predict(X_test))}\n')

'''
print(f'Val Accuracy: {acc_score}')
print(f'Val ROC AUC: {ra_score}')
'''