<a href="https://colab.research.google.com/github/edwinapalmer/DS-Unit-2-Linear-Models/blob/master/Logistic_Regression_EdwinaPalmer_LS_DS_214_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lambda School Data Science

*Unit 2, Sprint 1, Module 4*

---

# Logistic Regression


## Assignment ðŸŒ¯

You'll use a [**dataset of 400+ burrito reviews**](https://srcole.github.io/100burritos/). How accurately can you predict whether a burrito is rated 'Great'?

> We have developed a 10-dimensional system for rating the burritos in San Diego. ... Generate models for what makes a burrito great and investigate correlations in its dimensions.

- [ ] Do train/validate/test split. Train on reviews from 2016 & earlier. Validate on 2017. Test on 2018 & later.
- [ ] Begin with baselines for classification.
- [ ] Use scikit-learn for logistic regression.
- [ ] Get your model's validation accuracy. (Multiple times if you try multiple iterations.)
- [ ] Get your model's test accuracy. (One time, at the end.)
- [ ] Commit your notebook to your fork of the GitHub repo.


## Stretch Goals

- [ ] Add your own stretch goal(s) !
- [ ] Make exploratory visualizations.
- [ ] Do one-hot encoding.
- [ ] Do [feature scaling](https://scikit-learn.org/stable/modules/preprocessing.html).
- [ ] Get and plot your coefficients.
- [ ] Try [scikit-learn pipelines](https://scikit-learn.org/stable/modules/compose.html).

In [0]:
%%capture
import sys

# If you're on Colab:
if 'google.colab' in sys.modules:
    DATA_PATH = 'https://raw.githubusercontent.com/LambdaSchool/DS-Unit-2-Linear-Models/master/data/'
    !pip install category_encoders==2.*

# If you're working locally:
else:
    DATA_PATH = '../data/'

In [0]:
# Load data downloaded from https://srcole.github.io/100burritos/
import pandas as pd
df = pd.read_csv(DATA_PATH+'burritos/burritos.csv')

In [0]:
# Derive binary classification target:
# We define a 'Great' burrito as having an
# overall rating of 4 or higher, on a 5 point scale.
# Drop unrated burritos.
df = df.dropna(subset=['overall'])
df['Great'] = df['overall'] >= 4

In [0]:
# Clean/combine the Burrito categories
df['Burrito'] = df['Burrito'].str.lower()

california = df['Burrito'].str.contains('california')
asada = df['Burrito'].str.contains('asada')
surf = df['Burrito'].str.contains('surf')
carnitas = df['Burrito'].str.contains('carnitas')

df.loc[california, 'Burrito'] = 'California'
df.loc[asada, 'Burrito'] = 'Asada'
df.loc[surf, 'Burrito'] = 'Surf & Turf'
df.loc[carnitas, 'Burrito'] = 'Carnitas'
df.loc[~california & ~asada & ~surf & ~carnitas, 'Burrito'] = 'Other'

In [0]:
# Drop some high cardinality categoricals
df = df.drop(columns=['Notes', 'Location', 'Reviewer', 'Address', 'URL', 'Neighborhood'])

In [0]:
# Drop some columns to prevent "leakage"
df = df.drop(columns=['Rec', 'overall'])

In [180]:
df.head()

      Burrito       Date  Yelp  Google Chips  ...  Sushi  Avocado  Corn  Zucchini  Great
0  California  1/18/2016   3.5     4.2   NaN  ...    NaN      NaN   NaN       NaN  False
1  California  1/24/2016   3.5     3.3   NaN  ...    NaN      NaN   NaN       NaN  False
2    Carnitas  1/24/2016   NaN     NaN   NaN  ...    NaN      NaN   NaN       NaN  False
3       Asada  1/24/2016   NaN     NaN   NaN  ...    NaN      NaN   NaN       NaN  False
4  California  1/27/2016   4.0     3.8     x  ...    NaN      NaN   NaN       NaN   True

[5 rows x 59 columns]

In [0]:
df.drop(columns=['Yelp', 'Google', 'Chips', 'Cost', 'Unreliable', 'NonSD', 'Fries'], inplace=True)

In [182]:
df.head()

      Burrito       Date  Hunger  Mass (g)  ...  Avocado  Corn  Zucchini  Great
0  California  1/18/2016     3.0       NaN  ...      NaN   NaN       NaN  False
1  California  1/24/2016     3.5       NaN  ...      NaN   NaN       NaN  False
2    Carnitas  1/24/2016     1.5       NaN  ...      NaN   NaN       NaN  False
3       Asada  1/24/2016     2.0       NaN  ...      NaN   NaN       NaN  False
4  California  1/27/2016     4.0       NaN  ...      NaN   NaN       NaN   True

[5 rows x 52 columns]

In [0]:
from datetime import datetime

df.Date = pd.to_datetime(df.Date)

In [0]:
# To do train/validate/test split. 
#Train on reviews from 2016 & earlier.
#Validate on 2017.
#Test on 2018 & later.

train = df[df['Date'] <= '2016-12-31']
validate = df[(df['Date'] > '2016-12-31') & (df['Date'] <= '2017-12-31')]
test = df[df['Date'] > '2017-12-31']

In [185]:
train.shape, validate.shape, test.shape

((298, 52), (85, 52), (38, 52))

In [186]:
# Begin with baselines for classification.

from sklearn.metrics import accuracy_score

target = 'Great'
y_train = train[target]
y_validate = validate[target]
baseline, t = y_train.value_counts(normalize=True)
print (baseline)

0.5906040268456376

In [187]:
X_train.head()

      Burrito       Date  Hunger  Mass (g)  ...  Sushi  Avocado  Corn  Zucchini
0  California 2016-01-18     3.0       NaN  ...    NaN      NaN   NaN       NaN
1  California 2016-01-24     3.5       NaN  ...    NaN      NaN   NaN       NaN
2    Carnitas 2016-01-24     1.5       NaN  ...    NaN      NaN   NaN       NaN
3       Asada 2016-01-24     2.0       NaN  ...    NaN      NaN   NaN       NaN
4  California 2016-01-27     4.0       NaN  ...    NaN      NaN   NaN       NaN

[5 rows x 51 columns]

In [188]:
# To use scikit-learn for logistic regression

import category_encoders as ce

encoder = ce.OneHotEncoder(use_cat_names=True)

X_train = train[features]
X_validate = validate[features]
X_test = test[features]

X_train_encoded = encoder.fit_transform(X_train)
X_validate_encoded = encoder.transform(X_validate)
X_test_encoded = encoder.transform(X_test)

X_train_encoded.head()

   Burrito_California  Burrito_Carnitas  ...  Zucchini_nan  Zucchini_x
0                   1                 0  ...             1           0
1                   1                 0  ...             1           0
2                   0                 1  ...             1           0
3                   0                 0  ...             1           0
4                   1                 0  ...             1           0

[5 rows x 110 columns]

In [189]:
encoder.get_params()

{'cols': ['Burrito',
  'Beef',
  'Pico',
  'Guac',
  'Cheese',
  'Sour cream',
  'Pork',
  'Chicken',
  'Shrimp',
  'Fish',
  'Rice',
  'Beans',
  'Lettuce',
  'Tomato',
  'Bell peper',
  'Carrots',
  'Cabbage',
  'Sauce',
  'Salsa.1',
  'Cilantro',
  'Onion',
  'Taquito',
  'Pineapple',
  'Ham',
  'Chile relleno',
  'Nopales',
  'Lobster',
  'Egg',
  'Mushroom',
  'Bacon',
  'Sushi',
  'Avocado',
  'Corn',
  'Zucchini'],
 'drop_invariant': False,
 'handle_missing': 'value',
 'handle_unknown': 'value',
 'return_df': True,
 'use_cat_names': True,
 'verbose': 0}

In [213]:
# Impute missing values

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='mean')
X_train_imputed = imputer.fit_transform(X_train_encoded)
X_validate_imputed = imputer.transform(X_validate_encoded)

imputer.get_params()

TypeError: ignored

In [0]:
from sklearn.linear_model import LogisticRegression

y_validate = validate[target]
features = train.columns.drop([target])
X_train = train[features]
X_validate = validate[features]

In [198]:
# logistic regression

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_imputed)
X_validate_scaled = scaler.transform(X_validate_imputed)
X_test_scaled = scaler.transform(X_test_imputed)

y_validate = validate[target]
model = LogisticRegression()
model.fit(X_train_scaled, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [194]:
# To get your model's validation accuracy.

y_pred = model.predict(X_validate_scaled)
accuracy_score(y_validate, y_pred)

0.8470588235294118

In [207]:
# To get your model's test accuracy. (One time, at the end.)

y_pred = model.predict(X_test_scaled)
print(f'Test Accuracy Score: {model.score(X_test_scaled, y_pred)}')

Test Accuracy Score: 1.0