<a href="https://colab.research.google.com/github/LambdaTheda/DS-Unit-2-Linear-Models/blob/master/mon_mar_2_unit_2_build_pokemon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:

# Using Define ML problems (Unit 2, Sprint 3, Module 1)
# https://colab.research.google.com/drive/10xIG5cOmGnpSJG7BGrpZEGSvuT9X4Vdi#scrollTo=nCc3XZEyG3XV

'''
from urllib.request import urlopen
from zipfile import ZipFile
from io import BytesIO
import os.path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Read Data 
pokemon_url = 'https://www.kaggle.com/semioniy/predictemall'
pokemon_file = 'predictemall.zip'

if os.path.exists('predictemall.zip'):
    pokemon = pd.read_csv('predictemall.zip')
else: 
    z_pokemon = urlopen(pokemon_url)
    zip_pokemon = ZipFile(BytesIO(z_pokemon.read())).extract(pokemon_file)
    extractall()
    df = pd.read_csv(zip_pokemon)

df.head()
'''

In [0]:
from zipfile import ZipFile

# Create a ZipFile Object and load sample.zip in it
with ZipFile('predictemall.zip', 'r') as zipObj:
   # Extract all the contents of zip file in current directory
   zipObj.extractall()

print('Good JaAb, LadyFace!')

In [0]:
from google.colab import drive
drive.mount('/content/drive')

In [34]:
import pandas as pd

df = pd.read_csv('300k.csv')
df

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (49,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

        pokemonId   latitude   longitude  ... cooc_150 cooc_151  class
0              16  20.525745  -97.460829  ...    False    False   16.0
1             133  20.523695  -97.461167  ...    False    False  133.0
2              16  38.903590  -77.199780  ...    False    False   16.0
3              13  47.665903 -122.312561  ...    False    False   13.0
4             133  47.666454 -122.311628  ...    False    False  133.0
...           ...        ...         ...  ...      ...      ...    ...
142050         42  49.585175   -1.268738  ...    False    False   42.0
142051         13  51.120507   13.788891  ...    False    False   13.0
142052         29  48.855073    2.298065  ...    False    False   29.0
142053         19  44.156532   12.430401  ...    False    False   19.0
142054        120  38.896477  -77.068454  ...      NaN      NaN    NaN

[142055 rows x 208 columns]

In [35]:
df.shape

(142055, 208)

In [36]:
df.head()

   pokemonId   latitude   longitude  ... cooc_150 cooc_151  class
0         16  20.525745  -97.460829  ...    False    False   16.0
1        133  20.523695  -97.461167  ...    False    False  133.0
2         16  38.903590  -77.199780  ...    False    False   16.0
3         13  47.665903 -122.312561  ...    False    False   13.0
4        133  47.666454 -122.311628  ...    False    False  133.0

[5 rows x 208 columns]

In [37]:
#pd.options.display.max_columns = None
pd.set_option('display.max_columns', len(df.columns))
df.columns

Index(['pokemonId', 'latitude', 'longitude', 'appearedLocalTime', '_id',
       'cellId_90m', 'cellId_180m', 'cellId_370m', 'cellId_730m',
       'cellId_1460m',
       ...
       'cooc_143', 'cooc_144', 'cooc_145', 'cooc_146', 'cooc_147', 'cooc_148',
       'cooc_149', 'cooc_150', 'cooc_151', 'class'],
      dtype='object', length=208)

In [49]:
#pd.options.display.max_columns = 208
pd.set_option('display.max_columns', len(df.columns))
df.isnull().sum().sort_values(ascending = False)

class                     1
cooc_96                   1
cooc_70                   1
cooc_71                   1
cooc_72                   1
cooc_73                   1
cooc_74                   1
cooc_75                   1
cooc_76                   1
cooc_77                   1
cooc_78                   1
cooc_79                   1
cooc_80                   1
cooc_81                   1
cooc_82                   1
cooc_83                   1
cooc_84                   1
cooc_85                   1
cooc_86                   1
cooc_87                   1
cooc_88                   1
cooc_89                   1
cooc_90                   1
cooc_91                   1
cooc_92                   1
cooc_93                   1
cooc_94                   1
cooc_69                   1
cooc_68                   1
cooc_67                   1
cooc_53                   1
cooc_42                   1
cooc_43                   1
cooc_44                   1
cooc_45                   1
cooc_46                   1
cooc_47                   1
cooc_151                  1
cooc_49                   1
cooc_50                   1
cooc_51                   1
cooc_52                   1
cooc_54                   1
cooc_66                   1
cooc_55                   1
cooc_56                   1
cooc_57                   1
cooc_58                   1
cooc_59                   1
cooc_60                   1
cooc_61                   1
cooc_62                   1
cooc_63                   1
cooc_64                   1
cooc_65                   1
cooc_95                   1
cooc_48                   1
cooc_97                   1
cooc_138                  1
cooc_127                  1
cooc_128                  1
cooc_129                  1
cooc_130                  1
cooc_131                  1
cooc_132                  1
cooc_133                  1
cooc_134                  1
cooc_135                  1
cooc_136                  1
cooc_137                  1
cooc_139                  1
cooc_125                  1
cooc_140                  1
cooc_141                  1
cooc_142                  1
cooc_143                  1
cooc_144                  1
cooc_145                  1
cooc_146                  1
cooc_147                  1
cooc_149                  1
cooc_150                  1
cooc_98                   1
cooc_126                  1
cooc_148                  1
cooc_124                  1
cooc_110                  1
cooc_99                   1
cooc_123                  1
cooc_100                  1
cooc_102                  1
cooc_103                  1
cooc_104                  1
cooc_105                  1
cooc_106                  1
cooc_107                  1
cooc_108                  1
cooc_109                  1
cooc_101                  1
cooc_111                  1
cooc_117                  1
cooc_112                  1
cooc_122                  1
cooc_119                  1
cooc_118                  1
cooc_120                  1
cooc_116                  1
cooc_115                  1
cooc_114                  1
cooc_113                  1
cooc_121                  1
windBearing               0
sunsetMinute              0
pressure                  0
weatherIcon               0
sunriseMinutesMidnight    0
sunriseHour               0
sunriseMinute             0
sunriseMinutesSince       0
sunsetMinutesMidnight     0
sunsetHour                0
midurban                  0
sunsetMinutesBefore       0
population_density        0
urban                     0
suburban                  0
rural                     0
gymDistanceKm             0
gymIn100m                 0
gymIn250m                 0
gymIn500m                 0
temperature               0
gymIn1000m                0
windSpeed                 0
appearedTimeOfDay         0
weather                   0
continent                 0
gymIn5000m                0
latitude                  0
longitude                 0
appearedLocalTime         0
_id                       0
cellId_90m                0
cellId_180m               0
cellId_370m               0
cellId_730m               0
cellId_1460m              0
cellId_2920m              0
cellId_5850m              0
appearedHour              0
appearedMinute            0
appearedDayOfWeek         0
appearedDay               0
appearedMonth             0
appearedYear              0
terrainType               0
closeToWater              0
city                      0
gymIn2500m                0
cooc_20                   0
pokestopDistanceKm        0
pokestopIn100m            0
cooc_21                   0
cooc_22                   0
cooc_23                   0
cooc_24                   0
cooc_25                   0
cooc_26                   0
cooc_27                   0
cooc_28                   0
cooc_29                   0
cooc_30                   0
cooc_31                   0
cooc_32                   0
cooc_33                   0
cooc_34                   0
cooc_35                   0
cooc_36                   0
cooc_37                   0
cooc_38                   0
cooc_39                   0
cooc_40                   0
cooc_41                   0
cooc_19                   0
cooc_18                   0
cooc_17                   0
cooc_5                    0
pokestopIn250m            0
pokestopIn500m            0
pokestopIn1000m           0
pokestopIn2500m           0
pokestopIn5000m           0
cooc_1                    0
cooc_2                    0
cooc_3                    0
cooc_4                    0
cooc_6                    0
cooc_16                   0
cooc_7                    0
cooc_8                    0
cooc_9                    0
cooc_10                   0
cooc_11                   0
cooc_12                   0
cooc_13                   0
cooc_14                   0
cooc_15                   0
pokemonId                 0
dtype: int64

In [41]:
 pd.options.display.max_rows

60

In [0]:
'''
from scipy.io import arff
import pandas as pd

data = arff.loadarff('300k.arff')
df_arff = pd.DataFrame(data[0])


ARFF stands for Attribute-Relation File Format. It is an ASCII 
text file that describes a list of instances sharing a set of attributes.

df_arff.head()
'''

In [0]:
'''
import numpy as np
import pandas as pd
from scipy.io.arff import loadarff 

raw_data = loadarff('300k.arff')
df_data = pd.DataFrame(raw_data[0])
'''

In [38]:
# Choose your target. Which column in your tabular dataset will you predict?
y = df['appearedDayOfWeek']
y

0         dummy_day
1         dummy_day
2         dummy_day
3         dummy_day
4         dummy_day
            ...
142050       Friday
142051       Friday
142052       Friday
142053       Friday
142054       Friday
Name: appearedDayOfWeek, Length: 142055, dtype: object

In [47]:
df['appearedDayOfWeek'].nunique()

4

In [0]:
'''
pd.set_option("display.max_rows", 142055)
print(df)
'''

In [48]:
df.appearedDayOfWeek.unique()

array(['dummy_day', 'Sunday', 'Saturday', 'Friday'], dtype=object)

In [53]:
# Fit a Classification model
# Try a shallow decision tree as a fast, first model

import category_encoders as ce
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split

target = 'appearedDayOfWeek'
features = ['appearedMonth', 'appearedYear', 'appearedDay', 'pokestopDistanceKm ', 'weather', 'Latitude', 'Longitude']

X_train, X_test, y_train, y_test = train_test_split(train[features], train[target])

pipeline = make_pipeline(
    ce.OrdinalEncoder(),
    SimpleImputer(strategy='most_frequent'),
    RandomForestClassifier()
)

pipeline.fit(X_train, y_train)
acc_score = pipeline.score(test[features], test[target])
ra_score = roc_auc_score(test[target], pipeline.predict(test[features]))

print(f'Test Accuracy: {pipeline.score(X_test, y_test)}')
print(f'Test ROC AUC: {roc_auc_score(y_test, pipeline.predict(X_test))}\n')

print(f'Val Accuracy: {acc_score}')
print(f'Val ROC AUC: {ra_score}')

ModuleNotFoundError: ignored