<a href="https://colab.research.google.com/github/LambdaTheda/DS-Unit-2-Linear-Models/blob/master/pt5_F_mar20_REGRSS2_unit2_spr1_mod2_212_assmnt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lambda School Data Science

*Unit 2, Sprint 1, Module 2*

---

# Regression 2

## Assignment

You'll continue to **predict how much it costs to rent an apartment in NYC,** using the dataset from renthop.com.

- [ ] Do train/test split. Use data from April & May 2016 to train. Use data from June 2016 to test.
- [ ] Engineer at least two new features. (See below for explanation & ideas.)
- [ ] Fit a linear regression model with at least two features.
- [ ] Get the model's coefficients and intercept.
- [ ] Get regression metrics RMSE, MAE, and $R^2$, for both the train and test data.
- [ ] What's the best test MAE you can get? Share your score and features used with your cohort on Slack!
- [ ] As always, commit your notebook to your fork of the GitHub repo.


#### [Feature Engineering](https://en.wikipedia.org/wiki/Feature_engineering)

> "Some machine learning projects succeed and some fail. What makes the difference? Easily the most important factor is the features used." — Pedro Domingos, ["A Few Useful Things to Know about Machine Learning"](https://homes.cs.washington.edu/~pedrod/papers/cacm12.pdf)

> "Coming up with features is difficult, time-consuming, requires expert knowledge. 'Applied machine learning' is basically feature engineering." — Andrew Ng, [Machine Learning and AI via Brain simulations](https://forum.stanford.edu/events/2011/2011slides/plenary/2011plenaryNg.pdf) 

> Feature engineering is the process of using domain knowledge of the data to create features that make machine learning algorithms work. 

#### Feature Ideas
- Does the apartment have a description?
- How long is the description?
- How many total perks does each apartment have?
- Are cats _or_ dogs allowed?
- Are cats _and_ dogs allowed?
- Total number of rooms (beds + baths)
- Ratio of beds to baths
- What's the neighborhood, based on address or latitude & longitude?

## Stretch Goals
- [ ] If you want more math, skim [_An Introduction to Statistical Learning_](http://faculty.marshall.usc.edu/gareth-james/ISL/ISLR%20Seventh%20Printing.pdf),  Chapter 3.1, Simple Linear Regression, & Chapter 3.2, Multiple Linear Regression
- [ ] If you want more introduction, watch [Brandon Foltz, Statistics 101: Simple Linear Regression](https://www.youtube.com/watch?v=ZkjP5RJLQF4)
(20 minutes, over 1 million views)
- [ ] Add your own stretch goal(s) !

In [0]:
%%capture
import sys

# If you're on Colab:
if 'google.colab' in sys.modules:
    DATA_PATH = 'https://raw.githubusercontent.com/LambdaSchool/DS-Unit-2-Applied-Modeling/master/data/'
    !pip install category_encoders==2.*

# If you're working locally:
else:
    DATA_PATH = '../data/'
    
# Ignore this Numpy warning when using Plotly Express:
# FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
import warnings
warnings.filterwarnings(action='ignore', category=FutureWarning, module='numpy')

In [0]:
import numpy as np
import pandas as pd

# Read New York City apartment rental listing data
pd.set_option('display.max_rows', None)

df = pd.read_csv(DATA_PATH+'apartments/renthop-nyc.csv')
assert df.shape == (49352, 34)

# Remove the most extreme 1% prices,
# the most extreme .1% latitudes, &
# the most extreme .1% longitudes
df = df[(df['price'] >= np.percentile(df['price'], 0.5)) & 
        (df['price'] <= np.percentile(df['price'], 99.5)) & 
        (df['latitude'] >= np.percentile(df['latitude'], 0.05)) & 
        (df['latitude'] < np.percentile(df['latitude'], 99.95)) &
        (df['longitude'] >= np.percentile(df['longitude'], 0.05)) & 
        (df['longitude'] <= np.percentile(df['longitude'], 99.95))]

In [0]:
df.head(200)

In [0]:
df

In [0]:
df.shape

In [0]:
# Train/test split. Use data from April & May 2016 to train. 

df['created'] = pd.to_datetime(df['created'])
train = df[(df['created'].dt.year == 2016) & (df['created'].dt.month.isin([4, 5]))]
train.shape

In [0]:
# explore column to use for train/test split
df['created'].value_counts(48817) # returns counts as < 1 (bc of dt classes? or https://www.w3resource.com/pandas/series/series-value_counts.php- SERIES notdf fcngit)

In [0]:
df['created'].value_counts(48817).head(300)

In [0]:
# explore column to use for train/test split
df['created'].describe()

In [0]:
df['created'].shape

#  train/test split

In [0]:
#ATTEMPT 3: Parsing out only YEAR from df['created']-
df['created'] = pd.to_datetime(df['created']) #dot notation: df['created'] = pd.to_datetime(df.created); from https://www.youtube.com/watch?v=yCgJGsg0Xa4
df['year'] = df['created'].dt.year
df['year']

In [0]:
#temp df for making train set from df with df['created'].dt.year == 2016
df_train_yr = df[(df['year'] == 2016)]
df_train_yr.head(200)

In [0]:
df_train_yr.nunique

In [0]:
#df_train_yr.value_counts() #AttributeError: 'DataFrame' object has no attribute 'value_counts'; BC NO CLASSES ?#

In [0]:
#filter df_train_yr for April and May rows- WORKS
df_train_yr_and_months = df_train_yr[df_train_yr['created'].dt.month.isin([4, 5])]  #df[(df['year'] == 2016)]
df_train_yr_and_months.head(200)

In [0]:
df_train_yr_and_months.sample(300)

In [0]:
df_train = df_train_yr_and_months
df_train.head(300)

In [0]:
df_train.shape

# FILTER df_train TO MAKE TEST SET USING JUNE 2016 ROWS

In [0]:
# ATTEMPT 1: Use data from June 2016 to test- no rows! ASK WHY! bc df_train has only APR & MAY!
'''
df_test = df_train[(df_train['created'].dt.month == 6)]
df_test.head()
'''

In [0]:
df['created'] = pd.to_datetime(df['created'])
df['created'].dtype

In [0]:
# ATTEMPT 2: AttributeError: 'str' object has no attribute 'dt'
'''
df['created'] = pd.to_datetime(df['created'])

df['month'] = df['created'].dt.month

df_test = df_train_yr[df_train_yr['created'.dt.month] == 6] 
df_test
'''

In [0]:
# ATTEMPT 3: WORKS

df['created'] = pd.to_datetime(df['created'])
#df['created'].dtype            # RETURNS dtype('<M8[ns]')
df_test = df_train_yr[df_train_yr['created'].dt.month.isin([6])]
df_test.head(300)

In [0]:
df_test.shape

In [0]:
df_test['created'].value_counts()

# Engineer at least two new features.

In [0]:
# 1) Does the apartment have a description?

# Using for loop
# for descrp in range (len(df['description'])):  

# Chris suggests apply():

 # use regex to find '     ' string that seems to represent no descriptions
'''
import re 
no = re.compile('        ')
no    # RETURNS: re.compile(r'        ', re.UNICODE)
'''

re.compile(r'        ', re.UNICODE)

In [0]:
# set the new column to the dataframe column with all values EXCEPT '        '
df['has_description'] = ~df['description'].isin(['        '])

df['has_description'] = df['has_description'].map({True: 'Yes', False: 'No'})

df['has_description']

38874    Yes
40302    Yes
39067    Yes
34277    Yes
48618    Yes
37772    Yes
26186    Yes
43612    Yes
21470    Yes
17999    Yes
41152    Yes
26889    Yes
32154    Yes
6641     Yes
11051    Yes
10363    Yes
34925    Yes
4696     Yes
15310    Yes
37729    Yes
27670    Yes
26530    Yes
42044    Yes
6688     Yes
25352     No
17591    Yes
21462    Yes
36170    Yes
14425     No
47071    Yes
28986    Yes
43701    Yes
41654    Yes
4158     Yes
3075     Yes
47219    Yes
25627    Yes
39357    Yes
10693    Yes
18580    Yes
6598     Yes
25404    Yes
3141     Yes
35286     No
48836    Yes
27641    Yes
24424    Yes
42481    Yes
33673    Yes
21019    Yes
47009    Yes
43737    Yes
16126    Yes
45290    Yes
6418     Yes
21795    Yes
30783    Yes
14337    Yes
46785    Yes
30246    Yes
11426    Yes
4891     Yes
23430    Yes
877      Yes
22666    Yes
24917    Yes
15215    Yes
2443     Yes
28257    Yes
41788    Yes
5276     Yes
29055    Yes
5819     Yes
8475     Yes
32896    Yes
40037    Yes
43722    Yes
22517    Yes
40105    Yes
26719    Yes
47701    Yes
26279    Yes
18090    Yes
41397    Yes
2025     Yes
14746    Yes
16029    Yes
21278    Yes
43052    Yes
3258     Yes
15943    Yes
34457    Yes
49300    Yes
18812    Yes
2932     Yes
19832    Yes
10049    Yes
1682     Yes
15336    Yes
32175    Yes
11397    Yes
48295    Yes
17955    Yes
39813     No
21394    Yes
42637    Yes
17837    Yes
10814    Yes
34861    Yes
44542    Yes
28371    Yes
12771    Yes
9794     Yes
2693     Yes
35207    Yes
9651     Yes
30436    Yes
17243    Yes
13450    Yes
20573    Yes
4228     Yes
17107    Yes
28772    Yes
13790    Yes
32040    Yes
34135    Yes
7384     Yes
29443    Yes
14269    Yes
15117    Yes
14366    Yes
6724     Yes
10312    Yes
46364    Yes
3758     Yes
33209    Yes
22361    Yes
25449    Yes
27609    Yes
23990    Yes
22060    Yes
9812     Yes
8490      No
44593    Yes
46192     No
32319    Yes
26073    Yes
46523    Yes
34767    Yes
16473    Yes
29392    Yes
1619     Yes
38584    Yes
45316    Yes
18143    Yes
12256    Yes
25849    Yes
3955     Yes
6460     Yes
26991    Yes
37478    Yes
2799     Yes
26887    Yes
30138    Yes
11577    Yes
22936    Yes
10235    Yes
4436     Yes
2108     Yes
48322    Yes
34260    Yes
15642    Yes
33630    Yes
8731     Yes
14959    Yes
19400    Yes
35114    Yes
26620    Yes
1504     Yes
4665      No
6005     Yes
35724    Yes
28347    Yes
17259    Yes
37818    Yes
18725    Yes
17497    Yes
13231    Yes
47646     No
4703     Yes
48628    Yes
17052    Yes
4129     Yes
48676    Yes
47743    Yes
37424    Yes
49289    Yes
1755     Yes
23944    Yes
41173    Yes
Name: has_description, dtype: object

In [0]:
df.sample(200)

       bathrooms  bedrooms  ... total_rooms has_description
28497        1.0         2  ...         3.0             Yes
35127        2.0         2  ...         4.0             Yes
37480        1.0         2  ...         3.0             Yes
32816        1.0         2  ...         3.0             Yes
9085         1.0         1  ...         2.0             Yes
28619        1.0         1  ...         2.0             Yes
41776        1.0         0  ...         1.0             Yes
49054        2.0         4  ...         6.0             Yes
11479        2.0         2  ...         4.0             Yes
34140        2.0         2  ...         4.0             Yes
41050        1.0         1  ...         2.0             Yes
2153         1.0         1  ...         2.0             Yes
31928        1.0         1  ...         2.0             Yes
1137         1.0         1  ...         2.0             Yes
3862         2.0         3  ...         5.0             Yes
41383        1.0         2  ...         3.0              No
25609        1.0         2  ...         3.0             Yes
28971        1.0         2  ...         3.0             Yes
14810        1.5         2  ...         3.5             Yes
46628        1.0         4  ...         5.0             Yes
25460        1.0         0  ...         1.0             Yes
27899        1.0         0  ...         1.0             Yes
23001        2.0         2  ...         4.0             Yes
33689        2.0         3  ...         5.0             Yes
45168        1.0         1  ...         2.0              No
8192         1.0         0  ...         1.0             Yes
8178         1.0         1  ...         2.0             Yes
19514        1.0         2  ...         3.0             Yes
36403        2.0         4  ...         6.0             Yes
33047        1.0         1  ...         2.0             Yes
25760        1.0         2  ...         3.0             Yes
25421        1.0         1  ...         2.0             Yes
24654        2.5         2  ...         4.5             Yes
21907        1.0         2  ...         3.0             Yes
13167        2.0         4  ...         6.0             Yes
5609         1.0         0  ...         1.0             Yes
34440        1.0         0  ...         1.0             Yes
30403        2.0         2  ...         4.0             Yes
15565        2.0         3  ...         5.0             Yes
19604        3.0         1  ...         4.0             Yes
19629        1.0         0  ...         1.0             Yes
17040        1.0         0  ...         1.0             Yes
38996        1.0         0  ...         1.0             Yes
37583        2.0         2  ...         4.0             Yes
44201        1.0         0  ...         1.0             Yes
28182        3.0         3  ...         6.0             Yes
43467        1.5         2  ...         3.5             Yes
7429         1.0         2  ...         3.0             Yes
40571        2.0         2  ...         4.0             Yes
31471        2.0         3  ...         5.0             Yes
23206        1.0         0  ...         1.0             Yes
40070        1.0         0  ...         1.0             Yes
20577        1.0         2  ...         3.0             Yes
36077        1.0         4  ...         5.0             Yes
5133         2.0         2  ...         4.0             Yes
40137        2.0         4  ...         6.0             Yes
21863        1.0         1  ...         2.0             Yes
47662        1.0         1  ...         2.0             Yes
9517         1.0         3  ...         4.0             Yes
17385        1.0         1  ...         2.0             Yes
48194        1.0         1  ...         2.0             Yes
40159        1.0         0  ...         1.0             Yes
42592        1.0         2  ...         3.0             Yes
41058        1.0         0  ...         1.0             Yes
14155        1.0         3  ...         4.0             Yes
19706        1.0         0  ...         1.0             Yes
38855        2.0         4  ...         6.0             Yes
20765        1.0         0  ...         1.0             Yes
11314        3.0         3  ...         6.0             Yes
49307        1.0         2  ...         3.0             Yes
9320         1.0         1  ...         2.0             Yes
37212        0.0         0  ...         0.0              No
3094         1.0         0  ...         1.0             Yes
42854        2.0         4  ...         6.0             Yes
44102        1.0         1  ...         2.0             Yes
48361        1.0         1  ...         2.0             Yes
19901        1.0         0  ...         1.0             Yes
20337        3.0         2  ...         5.0             Yes
7042         1.0         2  ...         3.0             Yes
19           1.0         1  ...         2.0              No
10018        1.0         0  ...         1.0             Yes
8499         1.0         1  ...         2.0             Yes
10084        1.0         1  ...         2.0             Yes
41546        1.0         1  ...         2.0             Yes
4787         2.0         3  ...         5.0             Yes
13257        1.0         2  ...         3.0             Yes
18356        2.0         2  ...         4.0              No
19168        1.0         1  ...         2.0             Yes
7767         1.0         1  ...         2.0             Yes
22360        1.0         3  ...         4.0             Yes
41275        2.0         2  ...         4.0             Yes
20570        1.0         1  ...         2.0             Yes
43141        1.0         2  ...         3.0             Yes
41576        1.0         2  ...         3.0             Yes
42704        1.0         0  ...         1.0             Yes
9910         1.0         1  ...         2.0             Yes
48273        2.0         2  ...         4.0             Yes
32503        1.0         3  ...         4.0             Yes
47319        1.0         0  ...         1.0             Yes
39089        0.0         0  ...         0.0             Yes
47904        1.0         1  ...         2.0             Yes
4951         1.0         1  ...         2.0             Yes
3931         1.0         1  ...         2.0             Yes
9729         1.0         1  ...         2.0             Yes
4277         1.0         2  ...         3.0             Yes
9191         1.0         2  ...         3.0             Yes
32360        1.0         3  ...         4.0             Yes
32660        3.0         3  ...         6.0             Yes
33919        2.0         3  ...         5.0             Yes
2798         1.0         1  ...         2.0             Yes
24732        1.0         0  ...         1.0             Yes
39118        1.0         2  ...         3.0             Yes
38518        1.0         1  ...         2.0             Yes
46934        1.0         1  ...         2.0             Yes
28281        1.0         0  ...         1.0             Yes
36266        2.0         3  ...         5.0             Yes
33941        1.0         2  ...         3.0             Yes
15429        1.0         1  ...         2.0             Yes
7060         2.0         2  ...         4.0             Yes
43114        1.0         2  ...         3.0              No
49206        1.0         2  ...         3.0             Yes
35084        1.0         0  ...         1.0             Yes
21500        2.0         4  ...         6.0             Yes
2448         1.0         0  ...         1.0             Yes
5803         1.0         0  ...         1.0             Yes
5964         1.0         0  ...         1.0             Yes
18981        2.0         3  ...         5.0             Yes
44005        1.0         1  ...         2.0             Yes
34611        1.0         1  ...         2.0             Yes
9157         1.0         1  ...         2.0             Yes
8067         2.0         4  ...         6.0             Yes
45152        1.0         2  ...         3.0             Yes
36179        1.0         1  ...         2.0             Yes
45891        1.0         2  ...         3.0             Yes
3620         2.0         3  ...         5.0             Yes
34179        1.0         0  ...         1.0             Yes
32918        1.0         1  ...         2.0             Yes
17593        2.0         2  ...         4.0             Yes
42798        2.0         2  ...         4.0             Yes
19394        3.0         3  ...         6.0             Yes
46781        1.0         2  ...         3.0             Yes
12639        1.0         1  ...         2.0             Yes
31467        1.0         1  ...         2.0             Yes
8731         1.0         2  ...         3.0             Yes
3176         1.0         1  ...         2.0             Yes
17303        1.0         0  ...         1.0             Yes
37148        1.0         0  ...         1.0             Yes
1614         1.0         1  ...         2.0             Yes
32677        1.0         1  ...         2.0             Yes
6312         1.0         1  ...         2.0             Yes
48929        1.0         2  ...         3.0             Yes
29517        1.0         1  ...         2.0             Yes
6169         1.0         2  ...         3.0             Yes
13353        1.0         3  ...         4.0             Yes
17394        1.0         3  ...         4.0             Yes
5464         1.0         1  ...         2.0             Yes
21720        1.0         1  ...         2.0             Yes
43016        2.0         4  ...         6.0             Yes
29673        1.0         1  ...         2.0             Yes
21683        1.0         1  ...         2.0             Yes
35218        1.0         0  ...         1.0             Yes
15381        1.0         2  ...         3.0             Yes
37241        1.0         0  ...         1.0             Yes
11693        1.0         1  ...         2.0             Yes
1524         1.0         3  ...         4.0             Yes
41381        1.0         1  ...         2.0             Yes
32132        1.0         3  ...         4.0             Yes
12749        1.0         0  ...         1.0             Yes
13570        3.0         3  ...         6.0             Yes
4460         1.0         0  ...         1.0             Yes
10109        1.0         2  ...         3.0             Yes
18636        1.0         2  ...         3.0             Yes
27151        1.0         1  ...         2.0             Yes
23318        1.0         3  ...         4.0             Yes
39858        1.5         1  ...         2.5             Yes
31995        1.0         1  ...         2.0             Yes
48513        1.0         1  ...         2.0             Yes
38780        1.0         2  ...         3.0             Yes
33586        1.0         2  ...         3.0             Yes
36405        2.0         2  ...         4.0             Yes
48181        1.0         1  ...         2.0             Yes
35590        4.0         5  ...         9.0             Yes
32207        1.0         0  ...         1.0             Yes
22164        1.0         2  ...         3.0             Yes
10356        2.0         4  ...         6.0             Yes
457          1.0         2  ...         3.0             Yes
27052        1.0         1  ...         2.0             Yes
31258        1.0         1  ...         2.0             Yes
43296        1.0         3  ...         4.0              No
18734        1.0         2  ...         3.0             Yes
43685        2.0         2  ...         4.0             Yes
24076        2.0         3  ...         5.0             Yes
2126         1.0         1  ...         2.0             Yes
17074        1.0         1  ...         2.0             Yes
8846         1.0         0  ...         1.0             Yes
41335        4.0         4  ...         8.0             Yes
37292        1.0         0  ...         1.0             Yes
881          1.0         1  ...         2.0              No
18968        1.0         2  ...         3.0             Yes
24760        1.0         1  ...         2.0             Yes

[200 rows x 37 columns]

In [0]:
# use findall() 
'''
no.findall('        ')
print(df['description'].no.findall('        ')) # RETURNS: AttributeError: 'Series' object has no attribute 'no'
'''

In [0]:
# 2) Total number of rooms (beds + baths)
df['total_rooms'] = df['bedrooms'] + df['bathrooms']
df.head()

   bathrooms  bedrooms  ...  year total_rooms
0        1.5         3  ...  2016         4.5
1        1.0         2  ...  2016         3.0
2        1.0         1  ...  2016         2.0
3        1.0         1  ...  2016         2.0
4        1.0         4  ...  2016         5.0

[5 rows x 36 columns]

In [0]:
df.loc[1, 'description'] # RETURNS: '        '

'        '

In [0]:
df['description'].dtype # RETURNS: dtype('O'), A STRING

dtype('O')