<a href="https://colab.research.google.com/github/mtoce/DS-Unit-2-Linear-Models/blob/master/module4-logistic-regression/214_assig_LS_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lambda School Data Science

*Unit 2, Sprint 1, Module 4*

---

# Logistic Regression


## Assignment ðŸŒ¯

You'll use a [**dataset of 400+ burrito reviews**](https://srcole.github.io/100burritos/). How accurately can you predict whether a burrito is rated 'Great'?

> We have developed a 10-dimensional system for rating the burritos in San Diego. ... Generate models for what makes a burrito great and investigate correlations in its dimensions.

- [ ] Do train/validate/test split. Train on reviews from 2016 & earlier. Validate on 2017. Test on 2018 & later.
- [ ] Begin with baselines for classification.
- [ ] Use scikit-learn for logistic regression.
- [ ] Get your model's validation accuracy. (Multiple times if you try multiple iterations.)
- [ ] Get your model's test accuracy. (One time, at the end.)
- [ ] Commit your notebook to your fork of the GitHub repo.


## Stretch Goals

- [ ] Add your own stretch goal(s) !
- [ ] Make exploratory visualizations.
- [ ] Do one-hot encoding.
- [ ] Do [feature scaling](https://scikit-learn.org/stable/modules/preprocessing.html).
- [ ] Get and plot your coefficients.
- [ ] Try [scikit-learn pipelines](https://scikit-learn.org/stable/modules/compose.html).

# Load Data and Pre-Cleaning

In [0]:
%%capture
import sys
import category_encoders as cat

# If you're on Colab:
if 'google.colab' in sys.modules:
    DATA_PATH = 'https://raw.githubusercontent.com/LambdaSchool/DS-Unit-2-Linear-Models/master/data/'
    !pip install category_encoders==2.*

# If you're working locally:
else:
    DATA_PATH = '../data/'

In [0]:
# Load data downloaded from https://srcole.github.io/100burritos/
import pandas as pd
df = pd.read_csv(DATA_PATH+'burritos/burritos.csv')

In [0]:
# Derive binary classification target:
# We define a 'Great' burrito as having an
# overall rating of 4 or higher, on a 5 point scale.
# Drop unrated burritos.
df = df.dropna(subset=['overall'])
df['Great'] = df['overall'] >= 4

In [0]:
# Clean/combine the Burrito categories
df['Burrito'] = df['Burrito'].str.lower()

california = df['Burrito'].str.contains('california')
asada = df['Burrito'].str.contains('asada')
surf = df['Burrito'].str.contains('surf')
carnitas = df['Burrito'].str.contains('carnitas')

df.loc[california, 'Burrito'] = 'California'
df.loc[asada, 'Burrito'] = 'Asada'
df.loc[surf, 'Burrito'] = 'Surf & Turf'
df.loc[carnitas, 'Burrito'] = 'Carnitas'
df.loc[~california & ~asada & ~surf & ~carnitas, 'Burrito'] = 'Other'

In [0]:
# Drop some high cardinality categoricals
df = df.drop(columns=['Notes', 'Location', 'Reviewer', 'Address', 'URL', 'Neighborhood'])

In [0]:
# Drop some columns to prevent "leakage"
df = df.drop(columns=['Rec', 'overall'])

In [0]:
df_copy = df.copy()

In [424]:
df.head()

      Burrito       Date  Yelp  Google Chips  ...  Sushi  Avocado  Corn  Zucchini  Great
0  California  1/18/2016   3.5     4.2   NaN  ...    NaN      NaN   NaN       NaN  False
1  California  1/24/2016   3.5     3.3   NaN  ...    NaN      NaN   NaN       NaN  False
2    Carnitas  1/24/2016   NaN     NaN   NaN  ...    NaN      NaN   NaN       NaN  False
3       Asada  1/24/2016   NaN     NaN   NaN  ...    NaN      NaN   NaN       NaN  False
4  California  1/27/2016   4.0     3.8     x  ...    NaN      NaN   NaN       NaN   True

[5 rows x 59 columns]

In [425]:
df.shape

(421, 59)

In [0]:
#df.isnull().sum()

In [0]:
#df.dtypes

In [0]:
# let's figure out what columns to drop
# queso is a fully nan column. drop it.
df = df.drop(['Queso'], axis=1)

In [0]:
import numpy as np

In [430]:
df.shape

(421, 58)

In [431]:
df.head()

      Burrito       Date  Yelp  Google Chips  ...  Sushi  Avocado  Corn  Zucchini  Great
0  California  1/18/2016   3.5     4.2   NaN  ...    NaN      NaN   NaN       NaN  False
1  California  1/24/2016   3.5     3.3   NaN  ...    NaN      NaN   NaN       NaN  False
2    Carnitas  1/24/2016   NaN     NaN   NaN  ...    NaN      NaN   NaN       NaN  False
3       Asada  1/24/2016   NaN     NaN   NaN  ...    NaN      NaN   NaN       NaN  False
4  California  1/27/2016   4.0     3.8     x  ...    NaN      NaN   NaN       NaN   True

[5 rows x 58 columns]

# More Data Cleaning before Split

In [432]:
# look at mass and density columns that arent null
df[df['Mass (g)'].notnull()].head(10)

         Burrito       Date  Yelp  Google  ... Avocado  Corn  Zucchini  Great
322     Carnitas   3/3/2017   4.0     4.7  ...     NaN   NaN       NaN  False
323   California   3/3/2017   NaN     NaN  ...     NaN   NaN       NaN  False
325   California   4/7/2017   NaN     NaN  ...     NaN   NaN       NaN   True
326   California   4/7/2017   NaN     NaN  ...     NaN   NaN       NaN   True
328  Surf & Turf   4/7/2017   NaN     NaN  ...     NaN   NaN       NaN  False
333     Carnitas  4/25/2017   NaN     NaN  ...     NaN   NaN       NaN   True
335        Other  4/25/2017   NaN     NaN  ...     NaN   NaN       NaN  False
336        Other  4/25/2017   NaN     NaN  ...     NaN   NaN       NaN  False
341        Other  5/13/2017   4.5     5.0  ...     NaN   NaN       NaN  False
342        Other  5/17/2017   NaN     NaN  ...     NaN     x       NaN  False

[10 rows x 58 columns]

In [433]:
df.columns

Index(['Burrito', 'Date', 'Yelp', 'Google', 'Chips', 'Cost', 'Hunger',
       'Mass (g)', 'Density (g/mL)', 'Length', 'Circum', 'Volume', 'Tortilla',
       'Temp', 'Meat', 'Fillings', 'Meat:filling', 'Uniformity', 'Salsa',
       'Synergy', 'Wrap', 'Unreliable', 'NonSD', 'Beef', 'Pico', 'Guac',
       'Cheese', 'Fries', 'Sour cream', 'Pork', 'Chicken', 'Shrimp', 'Fish',
       'Rice', 'Beans', 'Lettuce', 'Tomato', 'Bell peper', 'Carrots',
       'Cabbage', 'Sauce', 'Salsa.1', 'Cilantro', 'Onion', 'Taquito',
       'Pineapple', 'Ham', 'Chile relleno', 'Nopales', 'Lobster', 'Egg',
       'Mushroom', 'Bacon', 'Sushi', 'Avocado', 'Corn', 'Zucchini', 'Great'],
      dtype='object')

In [0]:
# create lists to make data cleaning easier
mean_nan_replace = ['Mass (g)', 'Density (g/mL)', 'Length', 'Circum', 'Volume', 'Yelp', 'Google', 'Hunger', 'Temp', 'Meat', 'Fillings', 'Meat:filling', 'Uniformity', 'Salsa',
       'Synergy', 'Wrap', 'Cost']
zero_nan_replace = ['Chips', 'Tortilla', 'Beef', 'Pico', 'Guac', 
       'Cheese', 'Fries', 'Sour cream', 'Pork', 'Chicken', 'Shrimp', 'Fish',
       'Rice', 'Beans', 'Lettuce', 'Tomato', 'Bell peper', 'Carrots',
       'Cabbage', 'Sauce', 'Salsa.1', 'Cilantro', 'Onion', 'Taquito',
       'Pineapple', 'Ham', 'Chile relleno', 'Nopales', 'Lobster', 'Egg',
       'Mushroom', 'Bacon', 'Sushi', 'Avocado', 'Corn', 'Zucchini', 'NonSD', 'Unreliable']

In [0]:
# replace all NaNs in measurement of burrito with means
df[mean_nan_replace] = df[mean_nan_replace].fillna(value=df.mean())

In [0]:
# Fill all NaNs in burrito and Unreliable and NonSD in 
df[zero_nan_replace] = df[zero_nan_replace].fillna(value = 0)

In [0]:
df2 = pd.DataFrame()

In [0]:
# change all x's and X's in DF to 1's
df = df.replace({'x': 1, 'X': 1, 'yes': 1, 'Yes': 1, 'No': 0, 'no': 0, True: 1, False: 0, 'Other': 0})

# Train / Test / Validate Split

In [0]:
# we need to change date to a datetime object
df['Date'] = pd.to_datetime(df['Date'], infer_datetime_format=True)

In [0]:
# 3way split data
#df['Date'] = df['Date'].dt.year
train = df[df['Date'] == 2016]
test = df[(df['Date'] == 2018) | (df['Date'] == 2019)]
validate = df[df['Date'] == 2017]

print('train shape: ', train.shape)
print('test shape: ', test.shape)
print('validate shape: ', validate.shape)

# Baselines for Classification

In [0]:
# Define our target variable.
# We want to predict if a burrito is great so that column is our target
target = 'Great'

In [444]:
# lets get the baseline
baseline = df[target].value_counts(normalize=True)

0    0.567696
1    0.432304
Name: Great, dtype: float64

In [0]:
burrito_list = ['Burrito_California', 'Burrito_Carnitas', 'Burrito_Asada', 'Burrito_0',
       'Burrito_Surf & Turf']

In [0]:
features = ['Burrito', 'Date', 'Yelp', 'Google', 'Chips', 'Cost', 'Hunger',
       'Mass (g)', 'Density (g/mL)', 'Length', 'Circum', 'Volume', 'Tortilla',
       'Temp', 'Meat', 'Fillings', 'Meat:filling', 'Uniformity', 'Salsa', 
       'Wrap', 'Unreliable', 'NonSD', 'Beef', 'Pico', 'Guac',
       'Cheese', 'Fries', 'Sour cream', 'Pork', 'Chicken', 'Shrimp', 'Fish',
       'Rice', 'Beans', 'Lettuce', 'Tomato', 'Bell peper', 'Carrots',
       'Cabbage', 'Sauce', 'Salsa.1', 'Cilantro', 'Onion', 'Taquito',
       'Pineapple', 'Ham', 'Chile relleno', 'Nopales', 'Lobster', 'Egg',
       'Mushroom', 'Bacon', 'Sushi', 'Avocado', 'Corn', 'Zucchini']

# define your variables were using for regression
X_train = train[features]
X_test = test[features]
X_val = validate[features]
y_train = train[target]
y_test = test[target]
y_val = validate[target]

# Logistic Regression

In [0]:
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.metrics import accuracy_score
import category_encoders as cat

In [466]:
# One hot encocde features and then run logistic regression
encoder = cat.OneHotEncoder(use_cat_names=True)
X_train = encoder.fit_transform(X_train)
X_val = encoder.transform(X_val)
X_test = encoder.transform(X_test)

# logistic regression
log_reg = LogisticRegression(solver='lbfgs')
log_reg.fit(X_train, y_train)
print('Validation Accuracy: ', log_reg.score(X_val, y_val))

Validation Accuracy:  0.8117647058823529

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)

In [0]:
# logistic regression on test data

In [0]:
y_pred = log_reg.predict(X_test)

In [469]:
X_test.shape

(37, 60)

In [472]:
y_pred

array([1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1])

In [473]:
print('Test Accuracy: ', log_reg.score(X_test, y_test))

Test Accuracy:  0.7837837837837838

In [479]:
accuracy_score(y_test, y_pred)

0.7837837837837838

# SelectKBest Features