<a href="https://colab.research.google.com/github/FuriouStyles/DS-Unit-2-Linear-Models/blob/master/module4-logistic-regression/Stephen_P_assignment_regression_classification_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lambda School Data Science

*Unit 2, Sprint 1, Module 4*

---

# Logistic Regression


## Assignment ðŸŒ¯

You'll use a [**dataset of 400+ burrito reviews**](https://srcole.github.io/100burritos/). How accurately can you predict whether a burrito is rated 'Great'?

> We have developed a 10-dimensional system for rating the burritos in San Diego. ... Generate models for what makes a burrito great and investigate correlations in its dimensions.

- [ ] Do train/validate/test split. Train on reviews from 2016 & earlier. Validate on 2017. Test on 2018 & later.
- [ ] Begin with baselines for classification.
- [ ] Use scikit-learn for logistic regression.
- [ ] Get your model's validation accuracy. (Multiple times if you try multiple iterations.)
- [ ] Get your model's test accuracy. (One time, at the end.)
- [ ] Commit your notebook to your fork of the GitHub repo.
- [ ] Watch Aaron's [video #1](https://www.youtube.com/watch?v=pREaWFli-5I) (12 minutes) & [video #2](https://www.youtube.com/watch?v=bDQgVt4hFgY) (9 minutes) to learn about the mathematics of Logistic Regression.


## Stretch Goals

- [ ] Add your own stretch goal(s) !
- [ ] Make exploratory visualizations.
- [ ] Do one-hot encoding.
- [ ] Do [feature scaling](https://scikit-learn.org/stable/modules/preprocessing.html).
- [ ] Get and plot your coefficients.
- [ ] Try [scikit-learn pipelines](https://scikit-learn.org/stable/modules/compose.html).

In [0]:
%%capture
import sys

# If you're on Colab:
if 'google.colab' in sys.modules:
    DATA_PATH = 'https://raw.githubusercontent.com/LambdaSchool/DS-Unit-2-Linear-Models/master/data/'
    !pip install category_encoders==2.*

# If you're working locally:
else:
    DATA_PATH = '../data/'

In [0]:
# Load data downloaded from https://srcole.github.io/100burritos/
import pandas as pd
import numpy as np
df = pd.read_csv(DATA_PATH+'burritos/burritos.csv')

In [3]:
df.head()

               Location      Burrito       Date  ... Avocado Corn Zucchini
0    Donato's taco shop  California   1/18/2016  ...     NaN  NaN      NaN
1  Oscar's Mexican food  California   1/24/2016  ...     NaN  NaN      NaN
2  Oscar's Mexican food     Carnitas  1/24/2016  ...     NaN  NaN      NaN
3  Oscar's Mexican food  Carne asada  1/24/2016  ...     NaN  NaN      NaN
4          Pollos Maria   California  1/27/2016  ...     NaN  NaN      NaN

[5 rows x 66 columns]

In [0]:
# Derive binary classification target:
# We define a 'Great' burrito as having an
# overall rating of 4 or higher, on a 5 point scale.
# Drop unrated burritos.
df = df.dropna(subset=['overall'])
df['Great'] = df['overall'] >= 4

In [0]:
# Clean/combine the Burrito categories
df['Burrito'] = df['Burrito'].str.lower()

california = df['Burrito'].str.contains('california')
asada = df['Burrito'].str.contains('asada')
surf = df['Burrito'].str.contains('surf')
carnitas = df['Burrito'].str.contains('carnitas')

df.loc[california, 'Burrito'] = 'California'
df.loc[asada, 'Burrito'] = 'Asada'
df.loc[surf, 'Burrito'] = 'Surf & Turf'
df.loc[carnitas, 'Burrito'] = 'Carnitas'
df.loc[~california & ~asada & ~surf & ~carnitas, 'Burrito'] = 'Other'

In [0]:
# Drop some high cardinality categoricals
df = df.drop(columns=['Notes', 'Location', 'Mass (g)', 'Density (g/mL)', 'Reviewer', 'Address', 'URL', 'Neighborhood'])

In [0]:
# Drop some columns to prevent "leakage"
df = df.drop(columns=['Rec', 'overall'])

In [8]:
df.head(5)

      Burrito       Date  Yelp  Google Chips  ...  Sushi  Avocado  Corn  Zucchini  Great
0  California  1/18/2016   3.5     4.2   NaN  ...    NaN      NaN   NaN       NaN  False
1  California  1/24/2016   3.5     3.3   NaN  ...    NaN      NaN   NaN       NaN  False
2    Carnitas  1/24/2016   NaN     NaN   NaN  ...    NaN      NaN   NaN       NaN  False
3       Asada  1/24/2016   NaN     NaN   NaN  ...    NaN      NaN   NaN       NaN  False
4  California  1/27/2016   4.0     3.8     x  ...    NaN      NaN   NaN       NaN   True

[5 rows x 57 columns]

In [0]:
df.drop(columns=['Yelp', 'Google', 'Chips', 'Cost', 'Unreliable', 'NonSD', 'Fries'], inplace=True)

In [10]:
df.head()

      Burrito       Date  Hunger  Length  ...  Avocado  Corn  Zucchini  Great
0  California  1/18/2016     3.0     NaN  ...      NaN   NaN       NaN  False
1  California  1/24/2016     3.5     NaN  ...      NaN   NaN       NaN  False
2    Carnitas  1/24/2016     1.5     NaN  ...      NaN   NaN       NaN  False
3       Asada  1/24/2016     2.0     NaN  ...      NaN   NaN       NaN  False
4  California  1/27/2016     4.0     NaN  ...      NaN   NaN       NaN   True

[5 rows x 50 columns]

In [11]:
ing = ['Beef', 'Pico', 'Guac', 'Cheese', 'Sour cream', 'Pork', 'Chicken', 'Shrimp', 'Fish', 'Rice', 'Beans', 'Lettuce', 'Tomato', 'Bell peper', 'Carrots', 'Cabbage', 'Sauce', 'Salsa.1', 'Cilantro', 'Onion', 'Taquito', 'Pineapple', 'Ham', 'Chile relleno', 'Nopales', 'Lobster', 'Queso', 'Egg', 'Mushroom', 'Bacon', 'Sushi', 'Avocado', 'Corn', 'Zucchini']
for ing in df[ing]:
  df[ing][df[ing] == 'X'] = 1
  df[ing][df[ing] == 'x'] = 1
  df[ing] = pd.to_numeric(df[ing])
  df[ing] = df[ing].fillna(0)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.6/dist-packages/pandas/core/ops/__init__.py:1115: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)

In [0]:
df['Great'] = df['Great'].astype(int)

In [0]:
df['Date'] = pd.to_datetime(df['Date'])

In [0]:
from datetime import datetime

date1 = datetime.strptime('12/31/2016', '%m/%d/%Y')
date2 = datetime.strptime('12/31/2017', '%m/%d/%Y')

In [0]:
train = df[df['Date'] <= date1]
val = df[(date1 < df['Date']) & (df['Date'] <= date2)]
test = df[df['Date'] > date2]

In [16]:
train.drop(columns=['Date'], inplace=True)
val.drop(columns=['Date'], inplace=True)
test.drop(columns=['Great', 'Date'], inplace=True)

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:4117: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [17]:
train.shape, val.shape, test.shape

((298, 49), (85, 49), (38, 48))

In [18]:
from sklearn.metrics import accuracy_score



target = 'Great'
features = train.columns.drop([target])

y_train = train[target]
majority_class = y_train.mode()[0]
y_pred = [majority_class]*len(y_train)
accuracy_score(y_train, y_pred)

0.5906040268456376

In [22]:
import category_encoders as ce

encoder = ce.OneHotEncoder()

X_train = train[features]
X_val = val[features]
X_test = test[features]

X_train_encoded = encoder.fit_transform(X_train)
X_val_encoded = encoder.transform(X_val)
X_test_encoded = encoder.transform(X_test)

X_train_encoded.head()

   Burrito_1  Burrito_2  Burrito_3  Burrito_4  ...  Sushi  Avocado  Corn  Zucchini
0          1          0          0          0  ...    0.0      0.0   0.0       0.0
1          1          0          0          0  ...    0.0      0.0   0.0       0.0
2          0          1          0          0  ...    0.0      0.0   0.0       0.0
3          0          0          1          0  ...    0.0      0.0   0.0       0.0
4          1          0          0          0  ...    0.0      0.0   0.0       0.0

[5 rows x 52 columns]

In [0]:
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

imputer = SimpleImputer()
X_train_imputed = imputer.fit_transform(X_train_encoded)
X_val_imputed = imputer.transform(X_val_encoded)
X_test_imputed = imputer.transform(X_test_encoded)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_imputed)
X_val_scaled = scaler.transform(X_val_imputed)
X_test_scaled = scaler.transform(X_test_imputed)

In [27]:
imputed_df = pd.DataFrame(X_train_imputed)
imputed_df.head()

    0    1    2    3    4    5          6   ...   45   46   47   48   49   50   51
0  1.0  0.0  0.0  0.0  0.0  3.0  19.829886  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1  1.0  0.0  0.0  0.0  0.0  3.5  19.829886  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2  0.0  1.0  0.0  0.0  0.0  1.5  19.829886  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  1.0  0.0  0.0  2.0  19.829886  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4  1.0  0.0  0.0  0.0  0.0  4.0  19.829886  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0

[5 rows x 52 columns]

In [30]:
from sklearn.linear_model import LogisticRegression

y_val = val[target]

model = LogisticRegression(class_weight=)
model.fit(X_train_scaled, y_train)
print(f'Model Accuracy Score: {model.score(X_val_scaled, y_val)}')

Model Accuracy Score: 0.7647058823529411

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

In [32]:
y_pred = model.predict(X_test_scaled)
print(f'Test Accuracy Score: {model.score(X_test_scaled, y_pred)}')

Test Accuracy Score: 1.0